MappingConf: # [all in feature_map.py]
  n_points: 300  # Number of grid cells per dim
  size: 60 # in meters, size of the map per dim
  agent_radius: 0.32  # in meters
  blur_kernel_size: 0.05  # in meters
  obstacle_map_threshold: 0.5 # in occpuancy value
  fully_explored_threshold: 0.3  #
  checked_map_threshold: 0.3  #
  depth_factor: 0.01  #
  gradient_factor: 0.1
  optimal_object_distance: 2.0
  optimal_object_factor: 2.5
  obstacle_min: -0.3
  obstacle_max: 1.3
  filter_stairs: False
  floor_level: -0.88
  floor_threshold: -1.1
